name: Docker Image CI

on:
  release:
    types: [ published ]

jobs:

  build-and-publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build the Docker image
      run: |
        docker build . --file prod.Dockerfile --tag butter/front:latest \
                                           --tag butter/front:${{ github.event.release.tag_name }}

    - name: Push the Docker image (latest)
      run: docker push butter/front:latest

    - name: Push the Docker image (release tag)
      run: docker push butter/front:${{ github.event.release.tag_name }}
